(("default" . ((user-emacs-directory . "~/.emacs-configs/basic")))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs-configs/spacemacs")))
 ("castlemacs" . ((user-emacs-directory . "~/.emacs-configs/castlemacs")))
 ("spacemacs-clean" . ((user-emacs-directory . "~/.emacs-configs/spacemacs-develop-clean")))
 ("basic" . ((user-emacs-directory . "~/.emacs-configs/basic")))
 ("prelude" . ((user-emacs-directory . "~/.emacs-configs/prelude")))
 ("mine" . ((user-emacs-directory . "~/.emacs-configs/mine")))
 ("bare" . ((user-emacs-directory . "~/.emacs-configs/bare")))
 ("emacs-from-scratch" . ((user-emacs-directory . "~/.emacs-configs/emacs-from-scratch")))
 ("suyashbire1" . ((user-emacs-directory . "~/.emacs-configs/suyashbire1")))
 ("doom" . ((user-emacs-directory . "~/.emacs-configs/doom") (env . (("DOOMDIR" . "~/.doom.d"))))))
