#!/usr/bin/ruby
require 'irb/completion'
require 'irb/ext/save-history'
 
IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
# IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:AUTO_INDENT] = true

class Object
  # list methods which aren't in superclass
  def local_methods(obj = self)
    (obj.methods - obj.class.superclass.instance_methods).sort
  end

  def __edit_method(method_name, object=self)
    method = object.method(method_name.to_sym)
    `open txmt://open?url=file://#{method.__file__}&line=#{method.__line__}`
  end
end

railsrc = "~/.railsrc"
load railsrc if $0 == 'irb' && ENV['RAILS_ENV']
