#!/usr/bin/env zsh

for found in ~/.dotfiles/dotfiles/*; do
  ln -fs $found ~/.$found:t
done

mkdir -p ~/bin
ln -fs /usr/local/share/git-core/contrib/diff-highlight/diff-highlight ~/bin/diff-highlight

mkdir -p ~/.config
ln -fs doom.d ~/.doom.d
ln -fs fish ~/.config/fish
ln -fs omf ~/.config/omf

# mkdir -p ~/.ssh 
# ln -fs ~/.dotfiles/ssh/authorized_keys ~/.ssh/authorized_keys
