alias at0m="ssh james@lazyat0m.com"
alias atom="ssh lazyatom@lazyatom.com"
alias engines="ssh engines@rails-engines.org"
alias dust="ssh dust@lazyatom.com"
alias spillr="ssh -p 2222 lazyatom@france.illanti.com"
alias gh="github"